import OSforGFF.GFF.Package
import OSforGFF.CovarianceR
import GaussianField.Construction
import SchwartzNuclear

namespace OSforGFF
namespace GFF

open MeasureTheory Complex QFT

noncomputable section

variable (m : ℝ) [Fact (0 < m)]

namespace Adapter

open GaussianField

-- gaussian-field constructs measures using a separable Hilbert target.
-- We thread this as an explicit parameter so the adapter compiles even if Mathlib
-- doesn't provide it as a global instance for this particular `Lp`.
variable (hSep : TopologicalSpace.SeparableSpace (QFT.TargetHilbertSpace m))

-- Use the gaussian-field Dynin–Mityagin instance for Schwartz space.
-- This is needed only to *construct* `GaussianField.measure`; it is not exposed via `GFF.Package`.
local instance : DyninMityaginSpace TestFunction := by
  -- The instance is provided by `SchwartzNuclear`.
  -- Unfold `TestFunction = SchwartzMap SpaceTime ℝ` to match the gaussian-field statement.
  dsimp [TestFunction]
  infer_instance

-- Use the cylindrical σ-algebra from gaussian-field (generated by evaluations).
local instance : MeasurableSpace FieldConfiguration :=
  GaussianField.instMeasurableSpaceConfiguration (E := TestFunction)

/-- The gaussian-field measure (as a `ProbabilityMeasure`) specialized to the square-root propagator
embedding. -/
noncomputable def μGF : ProbabilityMeasure FieldConfiguration :=
  by
    classical
    letI : TopologicalSpace.SeparableSpace (QFT.TargetHilbertSpace m) := hSep
    exact ⟨GaussianField.measure (T := QFT.embeddingMapCLM m), by infer_instance⟩

/-- Build a `GFF.Package` from the gaussian-field backend specialized to the square-root
propagator embedding.

This is the concrete “adapter joint”: it turns `GaussianField.measure` + `GaussianField.charFun`
into the stable `GFF.Package` interface used by OS-facing proofs. -/
noncomputable def packageOfGaussianField : Package (m := m) :=
  { μ := μGF (m := m) (hSep := hSep)
    gff_real_characteristic := by
      intro f
      classical
      letI : TopologicalSpace.SeparableSpace (QFT.TargetHilbertSpace m) := hSep
      -- Start from gaussian-field `charFun` for the square-root propagator embedding.
      have h_char := GaussianField.charFun (T := QFT.embeddingMapCLM m) f
      -- Identify the covariance scalar: `freeCovarianceFormR m f f = ⟪T f, T f⟫_ℝ`.
      have h_cov :
          QFT.freeCovarianceFormR m f f =
            @inner ℝ (QFT.TargetHilbertSpace m) _ (QFT.embeddingMapCLM m f) (QFT.embeddingMapCLM m f) := by
        calc
          QFT.freeCovarianceFormR m f f
              = ‖QFT.embeddingMap m f‖ ^ 2 := QFT.freeCovarianceFormR_eq_normSq (m := m) f
          _ = ‖QFT.embeddingMapCLM m f‖ ^ 2 := by
              simp [QFT.embeddingMapCLM_apply]
          _ = @inner ℝ (QFT.TargetHilbertSpace m) _
                (QFT.embeddingMapCLM m f) (QFT.embeddingMapCLM m f) := by
              simpa [real_inner_self_eq_norm_sq] using
                (real_inner_self_eq_norm_sq (QFT.embeddingMapCLM m f)).symm
      -- Unfold the generating functional and rewrite using `h_char` and `h_cov`.
      -- LHS is exactly the gaussian-field integral (since `μGF` uses `GaussianField.measure`).
      -- RHS matches after rewriting the inner product using `h_cov`.
      simpa [μGF, GJGeneratingFunctional, distributionPairing, h_cov] using h_char }

end Adapter

end
end GFF
end OSforGFF

