/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import OSforGFF.Basic
import OSforGFF.WeakDualCylindrical
import Mathlib.MeasureTheory.MeasurableSpace.Pi

/-!
# Finite-dimensional cylinder API for `FieldConfiguration`

`FieldConfiguration` is defined as a weak dual of Schwartz test functions and equipped in
`OSforGFF.Basic` with the **cylindrical σ-algebra** generated by evaluation maps `ω ↦ ω φ`.

This file makes the finite-dimensional content explicit:

- measurability of the projection `ω ↦ (i ↦ ω (φ i))` into `ι → ℝ`,
- a `generateFrom` description of the cylindrical σ-algebra by `Fin n` cylinder sets.

These are the statements typically used when moving between characteristic functionals and
finite-dimensional distributions in the Minlos/GFF pipeline.
-/

namespace OSforGFF

open scoped BigOperators

noncomputable section

section

-- `FieldConfiguration` and `TestFunction` are from `OSforGFF.Basic`.

/-- Finite-dimensional projection of a field configuration along `fs : ι → TestFunction`. -/
def fieldProj {ι : Type*} (fs : ι → TestFunction) : FieldConfiguration → (ι → ℝ) :=
  fun ω i => ω (fs i)

@[measurability]
theorem measurable_fieldProj {ι : Type*} (fs : ι → TestFunction) :
    Measurable (fieldProj (fs := fs)) := by
  refine measurable_pi_iff.mpr ?_
  intro i
  simpa [fieldProj] using measurable_distributionPairing (a := fs i)

/-- `Fin n`-indexed cylinder generators for the cylindrical σ-algebra on `FieldConfiguration`. -/
def fieldFinCylinders : Set (Set FieldConfiguration) :=
  {s | ∃ n : ℕ, ∃ fs : Fin n → TestFunction, ∃ A : Set (Fin n → ℝ), MeasurableSet A ∧
      (fieldProj (fs := fs)) ⁻¹' A = s}

theorem fieldConfiguration_measurableSpace_eq_generateFrom_finCylinders :
    (inferInstance : MeasurableSpace FieldConfiguration) =
      MeasurableSpace.generateFrom fieldFinCylinders := by
  classical
  -- The `FieldConfiguration` measurable space is definitional to the cylindrical one on `WeakDual`,
  -- so we can reuse the general finite-cylinder characterization.
  change OSforGFF.weakDualCylMeasurableSpace (𝕜 := ℝ) (E := TestFunction) =
      MeasurableSpace.generateFrom fieldFinCylinders
  simpa [fieldFinCylinders, fieldProj, OSforGFF.weakDualFinCylinders, OSforGFF.weakDualProj] using
    (OSforGFF.weakDualCylMeasurableSpace_eq_generateFrom_finCylinders (𝕜 := ℝ) (E := TestFunction))

end

end

end OSforGFF

