/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/

import Mathlib.Analysis.LocallyConvex.WithSeminorms
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Data.Real.Sqrt

/-!
# Seminorm bounds from continuity (Gaussian setup)

If the (squared) covariance seminorm `f ↦ ‖T f‖²` is continuous and the topology on `E` is
generated by a family of seminorms `p`, then `f ↦ ‖T f‖` is bounded by a finite supremum of
seminorms from the family.

First step in relating the covariance to a *countable* generating family coming
from nuclearity hypotheses.
-/

open scoped BigOperators ENNReal NNReal

namespace OSforGFF

noncomputable section

namespace MinlosGaussianSeminormBounds

variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- If `f ↦ ‖T f‖²` is continuous, then `f ↦ ‖T f‖` is continuous. -/
theorem continuous_norm_of_continuous_norm_sq (T : E →ₗ[ℝ] H)
    (h_sq : Continuous fun f : E => (‖T f‖ ^ 2 : ℝ)) :
    Continuous fun f : E => ‖T f‖ := by
  have h_sqrt : Continuous fun f : E => Real.sqrt (‖T f‖ ^ 2 : ℝ) :=
    (Real.continuous_sqrt.comp h_sq)
  simpa [Real.sqrt_sq_eq_abs, abs_of_nonneg (norm_nonneg _)] using h_sqrt

/-- If the topology on `E` is generated by a family of seminorms `p` and `‖T ·‖` is continuous,
then it is controlled by finitely many seminorms from the family. -/
theorem seminorm_norm_comp_le_finset_sup
    {ι : Type*} (p : ι → Seminorm ℝ E) (hp : WithSeminorms p)
    (T : E →ₗ[ℝ] H)
    (h_sq : Continuous fun f : E => (‖T f‖ ^ 2 : ℝ)) :
    ∃ s : Finset ι, ∃ C : ℝ≥0, C ≠ 0 ∧ (normSeminorm ℝ H).comp T ≤ C • s.sup p := by
  have hq : Continuous ((normSeminorm ℝ H).comp T) := by
    have : Continuous fun f : E => ((normSeminorm ℝ H).comp T) f := by
      simpa using (continuous_norm_of_continuous_norm_sq (E := E) (H := H) T h_sq)
    simpa using this
  exact Seminorm.bound_of_continuous (𝕜 := ℝ) (p := p) (hp := hp) ((normSeminorm ℝ H).comp T) hq

/-- In the common situation where the generating seminorm family is monotone (e.g. indexed by `ℕ`),
the finite supremum bound from `seminorm_norm_comp_le_finset_sup` can be replaced by a bound using
a **single** seminorm from the family. -/
theorem seminorm_norm_comp_le_single_nat
    (p : ℕ → Seminorm ℝ E) (hp : WithSeminorms p) (hpmono : Monotone p)
    (T : E →ₗ[ℝ] H)
    (h_sq : Continuous fun f : E => (‖T f‖ ^ 2 : ℝ)) :
    ∃ n : ℕ, ∃ C : ℝ≥0, C ≠ 0 ∧ (normSeminorm ℝ H).comp T ≤ C • p n := by
  rcases seminorm_norm_comp_le_finset_sup (E := E) (H := H) (p := p) hp T h_sq with ⟨s, C, hC0, hle⟩
  classical
  by_cases hs : s.Nonempty
  · refine ⟨s.max' hs, C, hC0, ?_⟩
    -- `s.sup p ≤ p (max' s)` by monotonicity.
    have hsup : s.sup p ≤ p (s.max' hs) := by
      refine Finset.sup_le ?_
      intro i hi
      exact hpmono (Finset.le_max' _ _ hi)
    -- Multiply the pointwise inequality by `C`.
    have hsupC : C • s.sup p ≤ C • p (s.max' hs) := by
      -- unfold the order on seminorms
      intro x
      have hx := hsup x
      -- scalar multiplication on seminorms is pointwise scalar multiplication on `ℝ`
      simpa [Seminorm.smul_apply, NNReal.smul_def, smul_eq_mul, mul_assoc] using
        (mul_le_mul_of_nonneg_left hx (show (0 : ℝ) ≤ C by exact_mod_cast C.2))
    exact hle.trans hsupC
  · -- If `s = ∅`, then `s.sup p = ⊥`, so the bound is already a single seminorm bound (trivially).
    have hs' : s = ∅ := Finset.not_nonempty_iff_eq_empty.mp hs
    refine ⟨0, C, hC0, ?_⟩
    -- In this case, `s.sup p = ⊥`, so the RHS in `hle` is `C • ⊥ = ⊥`.
    -- Hence the desired bound holds because `⊥ ≤ C • p 0`.
    have hsup : C • s.sup p ≤ C • p 0 := by
      subst hs'
      intro x
      -- `s.sup p = ⊥`, so the LHS is `0`, and the RHS is nonnegative.
      simp [Seminorm.smul_apply, NNReal.smul_def, smul_eq_mul, mul_nonneg]
    exact hle.trans hsup

end MinlosGaussianSeminormBounds

end

end OSforGFF
