/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OSforGFF contributors
-/

import PhysLean.Mathematics.Distribution.WeakDualMeasurable

/-!
# Cylindrical measurable space on `WeakDual`

For distribution-valued random fields (Gaussian measures, Minlos, OS reconstruction), the natural
σ-algebra on `WeakDual 𝕜 E` is the **cylindrical σ-algebra** generated by the evaluation maps
`ω ↦ ω f`.

This file provides:

- a named measurable space `weakDualCylMeasurableSpace` (no global instance),
- measurability of evaluations and the universal property
  `Measurable g ↔ ∀ f, Measurable (fun x => g x f)`,
- explicit finite-dimensional projection maps `ω ↦ (ω (fs i))` and a `generateFrom` description by
  finite-dimensional cylinder sets (`Fin n`), as used in finite-dimensional distribution arguments.
-/

namespace OSforGFF

section Cylindrical

variable {𝕜 : Type*} [CommSemiring 𝕜] [MeasurableSpace 𝕜] [TopologicalSpace 𝕜] [ContinuousAdd 𝕜]
variable [ContinuousConstSMul 𝕜 𝕜]
variable {E : Type*} [AddCommMonoid E] [Module 𝕜 E] [TopologicalSpace E]

-- This file is a compatibility layer: the canonical development lives in PhysLean.
-- We keep the historical `OSforGFF.*` names as definitional abbreviations.

abbrev weakDualCylMeasurableSpace : MeasurableSpace (WeakDual 𝕜 E) :=
  PhysLean.Mathematics.Distribution.weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E)

section

local instance : MeasurableSpace (WeakDual 𝕜 E) :=
  weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E)

@[measurability]
theorem measurable_weakDual_toFun :
    Measurable (fun ω : WeakDual 𝕜 E => fun f : E => ω f) :=
  PhysLean.Mathematics.Distribution.measurable_weakDual_toFun (𝕜 := 𝕜) (E := E)

@[measurability]
theorem measurable_weakDual_eval (f : E) :
    Measurable (fun ω : WeakDual 𝕜 E => ω f) :=
  PhysLean.Mathematics.Distribution.measurable_weakDual_eval (𝕜 := 𝕜) (E := E) f

theorem weakDual_measurable_iff_eval_measurable
    {X : Type*} [MeasurableSpace X] (g : X → WeakDual 𝕜 E) :
    Measurable g ↔ ∀ f : E, Measurable (fun x => g x f) :=
  PhysLean.Mathematics.Distribution.weakDual_measurable_iff_eval_measurable (𝕜 := 𝕜) (E := E) g

abbrev weakDualProj {ι : Type*} (fs : ι → E) : WeakDual 𝕜 E → (ι → 𝕜) :=
  PhysLean.Mathematics.Distribution.weakDualProj (𝕜 := 𝕜) (E := E) fs

@[measurability]
theorem measurable_weakDualProj {ι : Type*} (fs : ι → E) :
    Measurable (weakDualProj (𝕜 := 𝕜) (E := E) fs) :=
  PhysLean.Mathematics.Distribution.measurable_weakDualProj (𝕜 := 𝕜) (E := E) fs

abbrev weakDualFinCylinders : Set (Set (WeakDual 𝕜 E)) :=
  PhysLean.Mathematics.Distribution.weakDualFinCylinders (𝕜 := 𝕜) (E := E)

theorem weakDualCylMeasurableSpace_eq_generateFrom_finCylinders :
    weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E) =
      MeasurableSpace.generateFrom (weakDualFinCylinders (𝕜 := 𝕜) (E := E)) :=
  PhysLean.Mathematics.Distribution.weakDualCylMeasurableSpace_eq_generateFrom_finCylinders (𝕜 := 𝕜)
    (E := E)

end

end Cylindrical

end OSforGFF

