import PhysLean.Mathematics.Distribution.WeakDualMeasurable

/-!
# Cylindrical measurable space on `WeakDual`

For a topological vector space `E` over `𝕜`, the weak dual `WeakDual 𝕜 E` is the space of
continuous linear functionals `E →L[𝕜] 𝕜`.

For probabilistic constructions (Gaussian measures, Minlos, etc.) the most *principled* default
σ-algebra on `WeakDual` is the **cylindrical σ-algebra**, i.e. the one generated by all evaluation
maps `ω ↦ ω f`.

This file equips `WeakDual 𝕜 E` with that measurable space (as a `comap` from the `pi`-space), and
provides the core API lemma: `weakDual_measurable_of_eval_measurable`.
-/

open scoped BigOperators

namespace PhysLean
namespace QFT

-- Re-export the cylindrical `WeakDual` measurable-space convention and its core API.
export PhysLean.Mathematics.Distribution
  (weakDualCylMeasurableSpace
    measurable_weakDual_toFun measurable_weakDual_eval
    weakDual_measurable_of_eval_measurable weakDual_measurable_iff_eval_measurable)

end QFT
end PhysLean

