/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/

import Mathlib.Topology.Algebra.Module.WeakDual
import Mathlib.MeasureTheory.MeasurableSpace.Pi

/-!
# Cylindrical measurable space on `WeakDual`

For a topological vector space `E` over `𝕜`, the weak dual `WeakDual 𝕜 E` is the space of
continuous linear functionals `E →L[𝕜] 𝕜`.

For probabilistic constructions (Gaussian measures, Minlos, etc.) the most principled default
σ-algebra on `WeakDual` is the **cylindrical σ-algebra**, i.e. the one generated by all evaluation
maps `ω ↦ ω f`.

This file defines that measurable space (as a `comap` from the `pi`-space) and provides the lemma
`weakDual_measurable_iff_eval_measurable`. We intentionally avoid installing a global
`MeasurableSpace (WeakDual 𝕜 E)` instance so that this cylindrical choice can coexist with other
measurable structures (e.g. Borel) without instance conflicts; users can work
definitionally with the lemmas in this file (or introduce a local instance via `letI`).
-/

namespace PhysLean
namespace Mathematics
namespace Distribution

section Cylindrical

variable {𝕜 : Type*} [CommSemiring 𝕜] [MeasurableSpace 𝕜] [TopologicalSpace 𝕜] [ContinuousAdd 𝕜]
variable [ContinuousConstSMul 𝕜 𝕜]
variable {E : Type*} [AddCommMonoid E] [Module 𝕜 E] [TopologicalSpace E]

/-- The cylindrical σ-algebra on `WeakDual 𝕜 E`: the `comap` of all evaluations `ω f`. -/
def weakDualCylMeasurableSpace : MeasurableSpace (WeakDual 𝕜 E) :=
  MeasurableSpace.comap (fun ω f => ω f) MeasurableSpace.pi

local instance : MeasurableSpace (WeakDual 𝕜 E) :=
  weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E)

@[measurability]
theorem measurable_weakDual_toFun : Measurable (fun ω : WeakDual 𝕜 E => fun f : E => ω f) := by
  intro s hs
  exact ⟨s, hs, rfl⟩

@[measurability]
theorem measurable_weakDual_eval (f : E) : Measurable (fun ω : WeakDual 𝕜 E => ω f) := by
  have h_toFun : Measurable (fun ω : WeakDual 𝕜 E => fun f : E => ω f) :=
    measurable_weakDual_toFun (𝕜 := 𝕜) (E := E)
  simpa using (measurable_pi_apply f).comp h_toFun

/-- To show measurability into `WeakDual`, it suffices to show that all
evaluations are measurable. -/
theorem weakDual_measurable_of_eval_measurable
    {X : Type*} [MeasurableSpace X] (g : X → WeakDual 𝕜 E)
    (h : ∀ f : E, Measurable (fun x => g x f)) :
    Measurable g := by
  have hpi : Measurable (fun x : X => fun f : E => g x f) := by
    exact (measurable_pi_iff.mpr h)
  rw [measurable_iff_comap_le]
  change (MeasurableSpace.comap (fun ω f => ω f) MeasurableSpace.pi).comap g ≤ (inferInstance : MeasurableSpace X)
  simpa [MeasurableSpace.comap_comp] using (measurable_iff_comap_le).1 hpi

/-- A map into `WeakDual` is measurable iff all evaluations are measurable. -/
theorem weakDual_measurable_iff_eval_measurable
    {X : Type*} [MeasurableSpace X] (g : X → WeakDual 𝕜 E) :
    Measurable g ↔ ∀ f : E, Measurable (fun x => g x f) := by
  constructor
  · intro hg f
    exact (measurable_weakDual_eval (𝕜 := 𝕜) (E := E) f).comp hg
  · intro h
    exact weakDual_measurable_of_eval_measurable (𝕜 := 𝕜) (E := E) g h

/-- Finite-dimensional projection of a `WeakDual` point along `fs : ι → E`. -/
def weakDualProj {ι : Type*} (fs : ι → E) : WeakDual 𝕜 E → (ι → 𝕜) :=
  fun ω i => ω (fs i)

@[measurability]
theorem measurable_weakDualProj {ι : Type*} (fs : ι → E) :
    Measurable (weakDualProj (𝕜 := 𝕜) (E := E) fs) := by
  refine measurable_pi_iff.mpr ?_
  intro i
  simpa [weakDualProj] using measurable_weakDual_eval (𝕜 := 𝕜) (E := E) (fs i)

/-- Cylinder sets generated by finite-dimensional projections `ω ↦ (ω (fs i))` for `i : Fin n`. -/
def weakDualFinCylinders : Set (Set (WeakDual 𝕜 E)) :=
  {s | ∃ n : ℕ, ∃ fs : Fin n → E, ∃ A : Set (Fin n → 𝕜), MeasurableSet A ∧
      (weakDualProj (𝕜 := 𝕜) (E := E) fs) ⁻¹' A = s}

theorem weakDualCylMeasurableSpace_eq_generateFrom_eval :
    weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E) =
      MeasurableSpace.generateFrom
        {s | ∃ (f : E) (A : Set 𝕜), MeasurableSet A ∧ (fun ω : WeakDual 𝕜 E => ω f) ⁻¹' A = s} := by
  have hpi :
      (MeasurableSpace.pi : MeasurableSpace (E → 𝕜)) =
        MeasurableSpace.generateFrom
          {B | ∃ (i : E) (A : Set 𝕜), MeasurableSet A ∧ Function.eval i ⁻¹' A = B} := by
    simpa using
      (MeasurableSpace.pi_eq_generateFrom_projections
        (ι := E) (α := fun _ : E => 𝕜) (mα := fun _ => (inferInstance : MeasurableSpace 𝕜)))
  apply le_antisymm
  · have :
        weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E) =
          MeasurableSpace.generateFrom
            ((Set.preimage fun ω : WeakDual 𝕜 E => fun f : E => ω f) ''
              {B | ∃ (i : E) (A : Set 𝕜), MeasurableSet A ∧ Function.eval i ⁻¹' A = B}) := by
      simp [weakDualCylMeasurableSpace, hpi, MeasurableSpace.comap_generateFrom]
    rw [this]
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨B, ⟨i, A, hA, rfl⟩, rfl⟩
    refine MeasurableSpace.measurableSet_generateFrom ?_
    refine ⟨i, A, hA, ?_⟩
    ext ω
    rfl
  · refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨f, A, hA, rfl⟩
    exact (measurable_weakDual_eval (𝕜 := 𝕜) (E := E) f) hA


theorem weakDualCylMeasurableSpace_eq_generateFrom_finCylinders :
    weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E) =
      MeasurableSpace.generateFrom (weakDualFinCylinders (𝕜 := 𝕜) (E := E)) := by
  have h_eval_le :
      MeasurableSpace.generateFrom
          {s | ∃ (f : E) (A : Set 𝕜), MeasurableSet A ∧ (fun ω : WeakDual 𝕜 E => ω f) ⁻¹' A = s} ≤
        MeasurableSpace.generateFrom (weakDualFinCylinders (𝕜 := 𝕜) (E := E)) := by
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨f, A, hA, rfl⟩
    have hA' : MeasurableSet ((fun x : Fin 1 → 𝕜 => x 0) ⁻¹' A) := by
      exact (measurable_pi_apply (0 : Fin 1)) hA
    refine MeasurableSpace.measurableSet_generateFrom ?_
    refine ⟨1, (fun _ : Fin 1 => f), (fun x : Fin 1 → 𝕜 => x 0) ⁻¹' A, hA', ?_⟩
    ext ω
    simp [weakDualProj]
  have h_fin_le :
      MeasurableSpace.generateFrom (weakDualFinCylinders (𝕜 := 𝕜) (E := E)) ≤
        weakDualCylMeasurableSpace (𝕜 := 𝕜) (E := E) := by
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨n, fs, A, hA, rfl⟩
    exact (measurable_weakDualProj (𝕜 := 𝕜) (E := E) fs) hA
  have h0 := weakDualCylMeasurableSpace_eq_generateFrom_eval (𝕜 := 𝕜) (E := E)
  refine le_antisymm ?_ h_fin_le
  simpa [h0] using h_eval_le

end Cylindrical

end Distribution
end Mathematics
end PhysLean
