/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/

import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.PSeries

import OSforGFF.NuclearSpace.Defs
import OSforGFF.NuclearSpace.Std

/-!
# A model nuclear Fréchet space: rapidly decreasing sequences

This file develops a **fully proved** model example of a `NuclearSpaceStd` in the sense used by the
Minlos/GFF pipeline: the space `RapidDecaySeq` of rapidly decreasing real sequences, endowed with
the Fréchet topology generated by weighted `ℓ²` seminorms.

The point is not to *assume* Schwartz nuclearity, but to build a solid, axiom-free nucleus that can
later be related to `TestFunction` once an explicit topological isomorphism (e.g. via Hermite
expansions) is available.
-/

open scoped BigOperators NNReal ENNReal

namespace OSforGFF

noncomputable section

/-! ## The space of rapidly decreasing sequences -/

local notation "H" => ℓ²(ℕ, ℝ)

/-- The weight \(w_k(n) = (n+1)^k\). -/
def weight (k : ℕ) (n : ℕ) : ℝ := ((n + 1 : ℝ) ^ k)

/-- Pointwise weighting of a sequence by `weight k`. -/
def weightFun (k : ℕ) (f : ℕ → ℝ) : ℕ → ℝ := fun n => weight k n * f n

@[simp]
lemma weight_zero (n : ℕ) : weight 0 n = 1 := by
  simp [weight]

@[simp]
lemma weight_succ (k n : ℕ) : weight (k + 1) n = weight k n * (n + 1) := by
  simp [weight, pow_succ]

/-- The submodule of sequences whose weighted versions are in `ℓ²` for every weight. -/
def RapidDecaySeq : Submodule ℝ (ℕ → ℝ) where
  carrier := { f | ∀ k : ℕ, Memℓp (weightFun k f) (2 : ℝ≥0∞) }
  zero_mem' := by
    intro k
    have h0 : weightFun k (0 : ℕ → ℝ) = 0 := by
      funext n
      simp [weightFun]
    simpa [h0] using (zero_memℓp (E := fun _ : ℕ => ℝ) (p := (2 : ℝ≥0∞)))
  add_mem' := by
    intro f g hf hg k
    have hfg : weightFun k (f + g) = weightFun k f + weightFun k g := by
      funext n
      simp [weightFun, mul_add]
    simpa [hfg] using (hf k).add (hg k)
  smul_mem' := by
    intro c f hf k
    have hsmul : weightFun k (c • f) = c • weightFun k f := by
      funext n
      simp [weightFun, mul_assoc, mul_comm]
    simpa [hsmul] using (hf k).const_smul c

/-! We use `RapidDecaySeq` as a **type** via the coercion `Submodule → Sort`. -/

namespace RapidDecaySeq

variable (k : ℕ)

/-- The canonical map to `ℓ²`: send a rapidly decreasing sequence to its `k`-weighted version. -/
noncomputable def toL2ₗ : RapidDecaySeq →ₗ[ℝ] H where
  toFun x := ⟨weightFun k x.1, x.2 k⟩
  map_add' x y := by
    ext n
    simp [weightFun, mul_add]
  map_smul' c x := by
    ext n
    simp [weightFun, mul_left_comm]

@[simp]
lemma toL2ₗ_apply (x : RapidDecaySeq) (n : ℕ) :
    (toL2ₗ k x : ℕ → ℝ) n = weight k n * x.1 n := rfl

/-- The weighted `ℓ²` seminorms generating the Fréchet topology. -/
noncomputable def seminorm : Seminorm ℝ RapidDecaySeq :=
  (normSeminorm ℝ H).comp (toL2ₗ k)

@[simp]
lemma seminorm_apply (x : RapidDecaySeq) :
    seminorm k x = ‖toL2ₗ k x‖ := by
  rfl

theorem seminorm_mono : Monotone (fun k : ℕ => seminorm k) := by
  intro a b hab x
  -- Compare the norms of the two weighted sequences pointwise.
  have hp : (0 : ℝ) < ((2 : ℝ≥0∞).toReal) := by norm_num
  let A : H := toL2ₗ a x
  let B : H := toL2ₗ b x
  have hAB :
      ‖A‖ ≤ ‖B‖ := by
    refine lp.norm_le_of_forall_sum_le (p := (2 : ℝ≥0∞)) hp (C := ‖B‖) (by positivity) ?_
    intro s
    have hpoint : ∀ n, ‖A n‖ ^ ((2 : ℝ≥0∞).toReal) ≤ ‖B n‖ ^ ((2 : ℝ≥0∞).toReal) := by
      intro n
      have hle_w : weight a n ≤ weight b n := by
        have h1 : (1 : ℝ) ≤ (n + 1 : ℝ) := by
          exact_mod_cast (Nat.succ_le_succ (Nat.zero_le n))
        simpa [weight] using (pow_le_pow_right₀ h1 hab)
      have hn : 0 ≤ weight a n := by
        have : 0 ≤ (n + 1 : ℝ) := by positivity
        simpa [weight] using pow_nonneg this a
      have hn' : 0 ≤ weight b n := by
        have : 0 ≤ (n + 1 : ℝ) := by positivity
        simpa [weight] using pow_nonneg this b
      have habs :
          ‖(weight a n * x.1 n)‖ ≤ ‖(weight b n * x.1 n)‖ := by
        simpa [Real.norm_eq_abs, abs_mul, abs_of_nonneg hn, abs_of_nonneg hn'] using
          mul_le_mul_of_nonneg_right hle_w (abs_nonneg (x.1 n))
      have : (‖weight a n * x.1 n‖) ^ ((2 : ℝ≥0∞).toReal)
            ≤ (‖weight b n * x.1 n‖) ^ ((2 : ℝ≥0∞).toReal) := by
        exact Real.rpow_le_rpow (norm_nonneg _) habs (by norm_num)
      simpa [A, B, toL2ₗ_apply] using this
    calc
      ∑ i ∈ s, ‖A i‖ ^ ((2 : ℝ≥0∞).toReal)
          ≤ ∑ i ∈ s, ‖B i‖ ^ ((2 : ℝ≥0∞).toReal) := by
              exact Finset.sum_le_sum fun i hi => hpoint i
      _ ≤ ‖B‖ ^ ((2 : ℝ≥0∞).toReal) := by
            simpa using (lp.sum_rpow_le_norm_rpow (p := (2 : ℝ≥0∞)) hp B s)
  simpa [seminorm, A, B] using hAB

/-! ## Topology generated by the seminorms -/

noncomputable instance (priority := 2000) : TopologicalSpace RapidDecaySeq :=
  (SeminormFamily.moduleFilterBasis (𝕜 := ℝ) (F := RapidDecaySeq) (p := fun k => seminorm k)).topology

theorem withSeminorms : WithSeminorms (fun k : ℕ => seminorm k) := by
  -- We *define* the topology to be the one induced by these seminorms.
  exact ⟨rfl⟩

/-! ## A diagonal nuclear operator on `ℓ²` -/

/-- Coefficients \(\sigma_s(n) = (n+1)^{-s}\). -/
def sigma (s : ℕ) (n : ℕ) : ℝ := ((weight s n)⁻¹)

@[simp]
lemma sigma_apply (s n : ℕ) : sigma s n = (weight s n)⁻¹ := rfl

lemma abs_sigma_le_one (s n : ℕ) : |sigma s n| ≤ 1 := by
  have hpos : 0 < weight s n := by
    have : 0 < (n + 1 : ℝ) := by exact_mod_cast (Nat.succ_pos n)
    simpa [weight] using (pow_pos this s)
  have hone : (1 : ℝ) ≤ weight s n := by
    have h1 : (1 : ℝ) ≤ (n + 1 : ℝ) := by
      exact_mod_cast (Nat.succ_le_succ (Nat.zero_le n))
    simpa [weight] using (one_le_pow₀ (a := (n + 1 : ℝ)) h1 (n := s))
  have : (weight s n)⁻¹ ≤ 1 := by
    simpa [one_div] using (inv_le_one_of_one_le₀ hone)
  simpa [sigma, abs_of_pos (inv_pos_of_pos hpos)] using this

/-- The diagonal linear map on `ℓ²` given by multiplying coordinates by `sigma s`. -/
noncomputable def diagPowInvₗ (s : ℕ) : H →ₗ[ℝ] H where
  toFun x :=
    ⟨fun n => sigma s n * x n, by
      have hp : (0 : ℝ) < ((2 : ℝ≥0∞).toReal) := by norm_num
      have hx : Summable (fun n : ℕ => ‖x n‖ ^ ((2 : ℝ≥0∞).toReal)) :=
        (lp.memℓp x).summable hp
      have hnonneg : ∀ n : ℕ, 0 ≤ ‖sigma s n * x n‖ ^ ((2 : ℝ≥0∞).toReal) := by
        intro n; positivity
      have hle : ∀ n : ℕ, ‖sigma s n * x n‖ ^ ((2 : ℝ≥0∞).toReal) ≤ ‖x n‖ ^ ((2 : ℝ≥0∞).toReal) := by
        intro n
        have : ‖sigma s n * x n‖ ≤ ‖x n‖ := by
          have hs : ‖sigma s n‖ ≤ 1 := by
            simpa [Real.norm_eq_abs] using abs_sigma_le_one (s := s) (n := n)
          calc
            ‖sigma s n * x n‖ = ‖sigma s n‖ * ‖x n‖ := by simp [norm_mul]
            _ ≤ 1 * ‖x n‖ := by gcongr
            _ = ‖x n‖ := by simp
        exact Real.rpow_le_rpow (norm_nonneg _) this (by norm_num)
      refine memℓp_gen (p := (2 : ℝ≥0∞)) ?_
      exact Summable.of_nonneg_of_le hnonneg hle hx⟩
  map_add' x y := by
    ext n
    change sigma s n * (x n + y n) = sigma s n * x n + sigma s n * y n
    simp [mul_add]
  map_smul' c x := by
    ext n
    simp [mul_left_comm]

@[simp]
lemma diagPowInvₗ_apply (s : ℕ) (x : H) (n : ℕ) :
  (diagPowInvₗ s x : ℕ → ℝ) n = sigma s n * x n := rfl

/-- The diagonal continuous linear map on `ℓ²` given by multiplying coordinates by `sigma s`. -/
noncomputable def diagPowInvCLM (s : ℕ) : H →L[ℝ] H := by
  refine (diagPowInvₗ s).mkContinuous 1 ?_
  intro x
  have hp : (0 : ℝ) < ((2 : ℝ≥0∞).toReal) := by norm_num
  let y : H := diagPowInvₗ s x
  have hy : ‖y‖ ≤ ‖x‖ := by
    refine lp.norm_le_of_forall_sum_le (p := (2 : ℝ≥0∞)) hp (C := ‖x‖) (by positivity) ?_
    intro t
    have hle_term : ∀ n : ℕ, ‖y n‖ ^ ((2 : ℝ≥0∞).toReal) ≤ ‖x n‖ ^ ((2 : ℝ≥0∞).toReal) := by
      intro n
      have : ‖y n‖ ≤ ‖x n‖ := by
        have hs' : ‖sigma s n‖ ≤ 1 := by
          simpa [Real.norm_eq_abs] using abs_sigma_le_one (s := s) (n := n)
        calc
          ‖y n‖ = ‖sigma s n * x n‖ := by simp [y, diagPowInvₗ_apply]
          _ = ‖sigma s n‖ * ‖x n‖ := by simp [norm_mul]
          _ ≤ 1 * ‖x n‖ := by gcongr
          _ = ‖x n‖ := by simp
      exact Real.rpow_le_rpow (norm_nonneg _) this (by norm_num)
    calc
      ∑ i ∈ t, ‖y i‖ ^ ((2 : ℝ≥0∞).toReal)
          ≤ ∑ i ∈ t, ‖x i‖ ^ ((2 : ℝ≥0∞).toReal) := by
              exact Finset.sum_le_sum fun i hi => hle_term i
      _ ≤ ‖x‖ ^ ((2 : ℝ≥0∞).toReal) := by
            simpa using (lp.sum_rpow_le_norm_rpow (p := (2 : ℝ≥0∞)) hp x t)
  simpa [y] using (hy.trans_eq (by simp))

@[simp]
lemma diagPowInvCLM_apply (s : ℕ) (x : H) (n : ℕ) :
  (diagPowInvCLM s x : ℕ → ℝ) n = sigma s n * x n := rfl

/-! ### Nuclearity of the diagonal map for `s > 1` -/

theorem summable_sigma_norm (s : ℕ) (hs : 1 < s) :
    Summable (fun n : ℕ => ‖sigma s n‖) := by
  have h : Summable (fun n : ℕ => ((n : ℝ) ^ s)⁻¹) := by
    exact (Real.summable_nat_pow_inv (p := s)).2 hs
  have h' : Summable (fun n : ℕ => ((n + 1 : ℝ) ^ s)⁻¹) := by
    have h₁ : Summable (fun n : ℕ => (((n + 1 : ℕ) : ℝ) ^ s)⁻¹) := by
      simpa using ((_root_.summable_nat_add_iff (f := fun n : ℕ => ((n : ℝ) ^ s)⁻¹) 1).2 h)
    simpa [Nat.cast_add_one] using h₁
  have hnorm : (fun n : ℕ => ‖sigma s n‖) = fun n : ℕ => ((n + 1 : ℝ) ^ s)⁻¹ := by
    funext n
    have hpos : 0 < weight s n := by
      have : 0 < (n + 1 : ℝ) := by exact_mod_cast (Nat.succ_pos n)
      simpa [weight] using (pow_pos this s)
    have hposInv : 0 < (weight s n)⁻¹ := inv_pos_of_pos hpos
    have : ‖sigma s n‖ = (weight s n)⁻¹ := by
      calc
        ‖sigma s n‖ = |sigma s n| := by simp [Real.norm_eq_abs]
        _ = |(weight s n)⁻¹| := by simp [sigma]
        _ = (weight s n)⁻¹ := abs_of_pos hposInv
    simpa [weight] using this
  rw [hnorm]
  exact h'

theorem isNuclearMap_diagPowInvCLM (s : ℕ) (hs : 1 < s) :
    IsNuclearMap (diagPowInvCLM s) := by
  classical
  -- Orthonormal coordinate vectors in `ℓ²`.
  haveI : Fact ((1 : ℝ≥0∞) ≤ (2 : ℝ≥0∞)) := ⟨by norm_num⟩
  let e : ℕ → H := fun n => lp.single (E := fun _ : ℕ => ℝ) 2 n (1 : ℝ)
  let φ : ℕ → (H →L[ℝ] ℝ) := fun n => innerSL ℝ (e n)
  let y : ℕ → H := fun n => (sigma s n) • e n
  refine ⟨φ, y, ?_, ?_⟩
  · have hφ : ∀ n, ‖φ n‖ = 1 := by
      intro n
      have : ‖e n‖ = 1 := by
        simp [e]
      simp [φ, this]
    have hy : ∀ n, ‖y n‖ = ‖sigma s n‖ := by
      intro n
      have : ‖e n‖ = 1 := by
        simp [e]
      simpa [y, this, norm_smul] using (by rfl : ‖(sigma s n) • e n‖ = ‖sigma s n‖ * ‖e n‖)
    have hsum : Summable (fun n : ℕ => ‖sigma s n‖) := summable_sigma_norm (s := s) hs
    refine (hsum.congr ?_)
    intro n
    simp [hφ n, hy n]
  · intro x
    have hx : HasSum (fun n : ℕ => lp.single 2 n ((diagPowInvCLM s x) n)) (diagPowInvCLM s x) :=
      lp.hasSum_single (E := fun _ : ℕ => ℝ) (p := (2 : ℝ≥0∞)) ENNReal.ofNat_ne_top (diagPowInvCLM s x)
    have hterm : ∀ n : ℕ, lp.single 2 n ((diagPowInvCLM s x) n) = (φ n x) • y n := by
      intro n
      have hφx : φ n x = x n := by
        simpa [φ, e, innerSL_apply_apply] using
          (lp.inner_single_left (𝕜 := ℝ) (ι := ℕ) (G := fun _ : ℕ => ℝ) n (1 : ℝ) x)
      have hs' :
          lp.single (E := fun _ : ℕ => ℝ) (2 : ℝ≥0∞) n ((weight s n)⁻¹ * x n) =
            ((weight s n)⁻¹ * x n) • lp.single (E := fun _ : ℕ => ℝ) (2 : ℝ≥0∞) n (1 : ℝ) := by
        simpa using
          (lp.single_smul (E := fun _ : ℕ => ℝ) (p := (2 : ℝ≥0∞)) n ((weight s n)⁻¹ * x n) (1 : ℝ))
      simp [y, e, diagPowInvCLM_apply, hφx, hs', sigma, smul_smul,
        mul_comm]
    have hx' : HasSum (fun n : ℕ => (φ n x) • y n) (diagPowInvCLM s x) :=
      HasSum.congr_fun hx (fun n => (hterm n).symm)
    exact hx'.tsum_eq.symm

/-!
## `RapidDecaySeq` is a standard nuclear Fréchet space

We now discharge the promise from the module header: the Fréchet space `RapidDecaySeq` (rapidly
decreasing sequences with `ℓ²`-weighted seminorms) is an instance of `NuclearSpaceStd`.

Idea:
- The local Banach space associated to the seminorm `seminorm k` identifies isometrically with `ℓ²`
  via the dense map `x ↦ weightFun k x`.
- Under this identification, the canonical inclusion from level `k+2` to level `k` becomes the
  diagonal map `diagPowInvCLM 2`, which is nuclear by `isNuclearMap_diagPowInvCLM`.
-/

open scoped Topology

-- NOTE: `RapidDecaySeq` already carries a Fréchet topology, so the quotient type
-- `QuotBySeminorm (seminorm k)` would also inherit a quotient topology.  For the Banach/completion
-- constructions in `OSforGFF.NuclearSpace.Defs`, we instead want the topology induced by the
-- quotient *norm*.
local instance (priority := 1001) (k : ℕ) :
    TopologicalSpace (QuotBySeminorm (E := RapidDecaySeq) (seminorm k)) :=
  (PseudoMetricSpace.toUniformSpace.toTopologicalSpace :
    TopologicalSpace (QuotBySeminorm (E := RapidDecaySeq) (seminorm k)))

/-! ### The quotient-level map into `ℓ²` -/

-- The quotient by `seminormKer (seminorm k)` maps linearly to `ℓ²` by applying `toL2ₗ k` to
-- representatives; this is well-defined since `seminorm k x = ‖toL2ₗ k x‖`.
noncomputable def toL2Quotₗ (k : ℕ) :
    QuotBySeminorm (E := RapidDecaySeq) (seminorm k) →ₗ[ℝ] H :=
  (seminormKer (E := RapidDecaySeq) (p := seminorm k)).liftQ (toL2ₗ k) (by
    intro x hx
    have hx0 : seminorm k x = 0 := hx
    have : ‖toL2ₗ k x‖ = 0 := by
      simpa [seminorm_apply] using hx0
    exact (norm_eq_zero.mp this))

@[simp] lemma toL2Quotₗ_mk (k : ℕ) (x : RapidDecaySeq) :
    toL2Quotₗ k (Submodule.Quotient.mk (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) x) =
      toL2ₗ k x := by
  simp [toL2Quotₗ]

lemma norm_toL2Quotₗ (k : ℕ) (x : QuotBySeminorm (E := RapidDecaySeq) (seminorm k)) :
    ‖toL2Quotₗ k x‖ = ‖x‖ := by
  refine Submodule.Quotient.induction_on (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) x ?_
  intro y
  have hy_norm :
      ‖(Submodule.Quotient.mk (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) y :
          QuotBySeminorm (E := RapidDecaySeq) (seminorm k))‖ = seminorm k y := by
    simpa using (QuotBySeminorm.norm_mk (E := RapidDecaySeq) (p := seminorm k) y)
  calc
    ‖toL2Quotₗ k (Submodule.Quotient.mk (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) y)‖
        = ‖toL2ₗ k y‖ := by simp [toL2Quotₗ_mk]
    _ = seminorm k y := by simp [seminorm_apply]
    _ = ‖(Submodule.Quotient.mk (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) y :
            QuotBySeminorm (E := RapidDecaySeq) (seminorm k))‖ := by simp [hy_norm]

lemma denseRange_toL2ₗ (k : ℕ) : DenseRange (toL2ₗ k) := by
  classical
  intro y
  haveI : Fact ((1 : ℝ≥0∞) ≤ (2 : ℝ≥0∞)) := ⟨by norm_num⟩
  have hy_hasSum :
      HasSum (fun n : ℕ => lp.single (E := fun _ : ℕ => ℝ) (2 : ℝ≥0∞) n (y n)) y :=
    lp.hasSum_single (E := fun _ : ℕ => ℝ) (p := (2 : ℝ≥0∞)) ENNReal.ofNat_ne_top y
  have hy_tendsto :
      Filter.Tendsto
        (fun N : ℕ =>
          ∑ n ∈ Finset.range N,
            lp.single (E := fun _ : ℕ => ℝ) (2 : ℝ≥0∞) n (y n))
        Filter.atTop (nhds y) :=
    hy_hasSum.tendsto_sum_nat
  have h_mem_range :
      ∀ N : ℕ,
        (∑ n ∈ Finset.range N, lp.single (E := fun _ : ℕ => ℝ) (2 : ℝ≥0∞) n (y n))
          ∈ Set.range (toL2ₗ k) := by
    intro N
    -- Define the preimage sequence `xN` by dividing the first `N` coordinates by the weight.
    let f : ℕ → ℝ := fun n => if n < N then (weight k n)⁻¹ * y n else 0
    have hf : ∀ j : ℕ, Memℓp (weightFun j f) (2 : ℝ≥0∞) := by
      intro j
      have hsum :
          Summable (fun n : ℕ => ‖(weightFun j f) n‖ ^ ((2 : ℝ≥0∞).toReal)) := by
        refine summable_of_finite_support <| (Set.finite_Iio N).subset ?_
        intro n hn
        have : n < N := by
          by_contra hge
          have hn' : ¬ n < N := hge
          have hf0 : f n = 0 := by simp [f, hn']
          have : (weightFun j f) n = 0 := by simp [weightFun, hf0]
          have : (‖(weightFun j f) n‖ ^ ((2 : ℝ≥0∞).toReal)) = 0 := by
            simp [this]
          exact hn (by simpa using this)
        exact this
      exact memℓp_gen (p := (2 : ℝ≥0∞)) hsum
    let xN : RapidDecaySeq := ⟨f, hf⟩
    refine ⟨xN, ?_⟩
    ext n
    by_cases hn : n < N
    · have hne : weight k n ≠ 0 := by
        have : (n + 1 : ℝ) ≠ 0 := by exact_mod_cast (Nat.succ_ne_zero n)
        simpa [weight] using (pow_ne_zero k this)
      have : (toL2ₗ k xN : ℕ → ℝ) n = y n := by
        calc
          (toL2ₗ k xN : ℕ → ℝ) n = weight k n * ((weight k n)⁻¹ * y n) := by
            simp [toL2ₗ_apply, xN, f, hn]
          _ = y n := by
            rw [← mul_assoc (weight k n) (weight k n)⁻¹ (y n)]
            simp [hne]
      simp [this, Finset.sum_apply, lp.coeFn_single, Finset.sum_pi_single, Finset.mem_range, hn]
    · have hn' : ¬ n < N := hn
      have : (toL2ₗ k xN : ℕ → ℝ) n = 0 := by
        simp [toL2ₗ_apply, xN, f, hn', weightFun]
      simpa [this, Finset.sum_apply, lp.coeFn_single, Finset.sum_pi_single, Finset.mem_range, hn']
  refine mem_closure_of_tendsto hy_tendsto (Filter.Eventually.of_forall h_mem_range)

lemma denseRange_toL2Quotₗ (k : ℕ) : DenseRange (toL2Quotₗ k) := by
  intro y
  have hy : y ∈ closure (Set.range (toL2ₗ k)) := denseRange_toL2ₗ (k := k) y
  have hrange : Set.range (toL2ₗ k) = Set.range (toL2Quotₗ k) := by
    ext z
    constructor
    · rintro ⟨x, rfl⟩
      refine ⟨Submodule.Quotient.mk (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) x, ?_⟩
      simp [toL2Quotₗ_mk]
    · rintro ⟨x, rfl⟩
      refine Submodule.Quotient.induction_on
        (p := seminormKer (E := RapidDecaySeq) (p := seminorm k)) x ?_
      intro x
      exact ⟨x, by simp [toL2Quotₗ_mk]⟩
  simpa [hrange] using hy

/-! ### An isometric identification `Banach(seminorm k) ≃ᵢ ℓ²` -/

-- Norm preservation for the canonical embedding into the completion.
lemma norm_coe_banachOfSeminorm
    (p : Seminorm ℝ RapidDecaySeq) (x : QuotBySeminorm (E := RapidDecaySeq) p) :
    ‖(x : BanachOfSeminorm (E := RapidDecaySeq) p)‖ = ‖x‖ := by
  have hIso :
      Isometry ((↑) :
        QuotBySeminorm (E := RapidDecaySeq) p → BanachOfSeminorm (E := RapidDecaySeq) p) :=
    UniformSpace.Completion.coe_isometry
  have hdist := hIso.dist_eq x (0 : QuotBySeminorm (E := RapidDecaySeq) p)
  simp [dist_eq_norm]

noncomputable def banachEquivL2 (k : ℕ) :
    BanachOfSeminorm (E := RapidDecaySeq) (seminorm k) ≃ₗᵢ[ℝ] H := by
  -- We work with `E = QuotBySeminorm (seminorm k)` and its linear map into `ℓ²`.
  let E : Type := QuotBySeminorm (E := RapidDecaySeq) (seminorm k)
  let T : E →ₗ[ℝ] H := toL2Quotₗ k
  let F : Submodule ℝ H := LinearMap.range T
  have hTnorm : ∀ x : E, ‖T x‖ = ‖x‖ := fun x => by simpa [T] using (norm_toL2Quotₗ (k := k) x)
  have hTinj : Function.Injective T := by
    intro x y hxy
    have : T (x - y) = 0 := by simp [map_sub, hxy]
    have h0 : ‖T (x - y)‖ = 0 := by
      simpa using congrArg (fun z : H => ‖z‖) this
    have hnorm0 : ‖x - y‖ = 0 := by
      calc
        ‖x - y‖ = ‖T (x - y)‖ := (hTnorm (x - y)).symm
        _ = 0 := h0
    simpa using sub_eq_zero.mp (norm_eq_zero.mp hnorm0)
  let f : E ≃ₗ[ℝ] F := LinearEquiv.ofInjective T hTinj
  -- Dense embeddings: quotient into its completion, and `F` into `ℓ²`.
  let e₁ : E →ₗ[ℝ] BanachOfSeminorm (E := RapidDecaySeq) (seminorm k) :=
    (BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm k)).toLinearMap
  let e₂ : F →ₗ[ℝ] H := (Submodule.subtype F)
  have h_dense₁ : DenseRange e₁ := by
    simpa [e₁] using (BanachOfSeminorm.denseRange_coeCLM (E := RapidDecaySeq) (p := seminorm k))
  have h_dense₂ : DenseRange e₂ := by
    have hT_dense : DenseRange T := by simpa [T] using denseRange_toL2Quotₗ (k := k)
    intro y
    have : y ∈ closure (Set.range T) := hT_dense y
    have hrange : Set.range e₂ = Set.range T := by
      ext z
      constructor
      · rintro ⟨u, rfl⟩
        simp [e₂]
      · rintro ⟨x, rfl⟩
        exact ⟨⟨T x, ⟨x, rfl⟩⟩, rfl⟩
    simpa [hrange] using this
  have h_norm : ∀ x : E, ‖e₂ (f x)‖ = ‖e₁ x‖ := by
    intro x
    have hleft : ‖e₂ (f x)‖ = ‖T x‖ := rfl
    have hright : ‖e₁ x‖ = ‖x‖ := by
      simp [e₁, BanachOfSeminorm.coeCLM]
    simp [hleft, hright, hTnorm x]
  exact (f.extendOfIsometry (σ₁₂ := RingHom.id ℝ) e₁ e₂ h_dense₁ h_dense₂ h_norm)

@[simp]
lemma banachEquivL2_apply_coe (k : ℕ)
    (x : QuotBySeminorm (E := RapidDecaySeq) (seminorm k)) :
    banachEquivL2 k
        (BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm k) x) = toL2Quotₗ k x := by
  change banachEquivL2 k
        ((↑(BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm k)) :
            QuotBySeminorm (E := RapidDecaySeq) (seminorm k) →ₗ[ℝ]
              BanachOfSeminorm (E := RapidDecaySeq) (seminorm k)) x)
      = toL2Quotₗ k x
  simp (config := { zeta := true }) [banachEquivL2]
  have hx :
      (BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm k) x) =
        ((↑(BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm k)) :
            QuotBySeminorm (E := RapidDecaySeq) (seminorm k) →ₗ[ℝ]
              BanachOfSeminorm (E := RapidDecaySeq) (seminorm k)) x) := rfl
  rw [hx]
  rw [LinearEquiv.extendOfIsometry_eq]
  rfl

/-! ### Nuclearity of the local inclusions -/

-- A key computation: under weights, the inclusion from level `k+2` to level `k` is diagonal.
lemma diagPowInvCLM_two_toL2 (k : ℕ) (x : RapidDecaySeq) :
    diagPowInvCLM 2 (toL2ₗ (k + 2) x) = toL2ₗ k x := by
  ext n
  have hn1 : (n + 1 : ℝ) ≠ 0 := by exact_mod_cast (Nat.succ_ne_zero n)
  have hne2 : weight 2 n ≠ 0 := by
    simpa [weight] using (pow_ne_zero 2 hn1)
  have hw : weight (k + 2) n = weight k n * weight 2 n := by
    dsimp [weight]
    exact pow_add (n + 1 : ℝ) k 2
  have hcoef : (weight 2 n)⁻¹ * weight (k + 2) n = weight k n := by
    rw [hw]
    calc
      (weight 2 n)⁻¹ * (weight k n * weight 2 n)
          = ((weight 2 n)⁻¹ * weight k n) * weight 2 n := by
              rw [← mul_assoc]
      _ = (weight k n * (weight 2 n)⁻¹) * weight 2 n := by
            simp [mul_comm]
      _ = weight k n * (weight 2 n)⁻¹ * weight 2 n := by
            rw [mul_assoc]
      _ = weight k n := by
            simpa [mul_assoc] using (inv_mul_cancel_right₀ (b := weight 2 n) hne2 (a := weight k n))
  have : (weight 2 n)⁻¹ * (weight (k + 2) n * x.1 n) = weight k n * x.1 n := by
    rw [← mul_assoc (weight 2 n)⁻¹ (weight (k + 2) n) (x.1 n)]
    rw [hcoef]
  simpa [diagPowInvCLM_apply, toL2ₗ_apply, sigma, mul_assoc] using this

theorem isNuclearMap_inclCLM_succ_succ (k : ℕ) :
    IsNuclearMap
      (BanachOfSeminorm.inclCLM (E := RapidDecaySeq)
        (p := seminorm (k + 2)) (q := seminorm k)
        (by
          simpa using (seminorm_mono (a := k) (b := k + 2) (Nat.le_add_right k 2)))) := by
  -- Identify the inclusion by conjugating the diagonal nuclear operator on `ℓ²`.
  let E₀ := BanachOfSeminorm (E := RapidDecaySeq) (seminorm (k + 2))
  let E₁ := BanachOfSeminorm (E := RapidDecaySeq) (seminorm k)
  let incl : E₀ →L[ℝ] E₁ :=
    BanachOfSeminorm.inclCLM (E := RapidDecaySeq)
      (p := seminorm (k + 2)) (q := seminorm k)
      (by
        simpa using (seminorm_mono (a := k) (b := k + 2) (Nat.le_add_right k 2)))
  let iso₀ : E₀ ≃ₗᵢ[ℝ] H := banachEquivL2 (k + 2)
  let iso₁ : E₁ ≃ₗᵢ[ℝ] H := banachEquivL2 k
  let iso₀L : E₀ →L[ℝ] H := iso₀.toContinuousLinearEquiv.toContinuousLinearMap
  let iso₁L : E₁ →L[ℝ] H := iso₁.toContinuousLinearEquiv.toContinuousLinearMap
  let iso₁Linv : H →L[ℝ] E₁ := iso₁.symm.toContinuousLinearEquiv.toContinuousLinearMap
  have h_conj :
      (iso₁L.comp incl) = (diagPowInvCLM 2).comp iso₀L := by
    apply ContinuousLinearMap.coeFn_injective
    have hd : DenseRange (BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm (k + 2))) :=
      BanachOfSeminorm.denseRange_coeCLM (E := RapidDecaySeq) (p := seminorm (k + 2))
    have hs : Dense (Set.range (BanachOfSeminorm.coeCLM (E := RapidDecaySeq) (seminorm (k + 2)))) := by
      refine dense_iff_closure_eq.2 ?_
      exact (denseRange_iff_closure_range).1 hd
    refine Continuous.ext_on hs (by fun_prop) (by fun_prop) ?_
    rintro _ ⟨xq, rfl⟩
    refine Submodule.Quotient.induction_on (p := seminormKer (E := RapidDecaySeq) (p := seminorm (k + 2))) xq ?_
    intro x
    simp [incl, iso₀, iso₁, iso₀L, iso₁L]
    rw [BanachOfSeminorm.inclCLM_coeCLM]
    simp [QuotBySeminorm.inclCLM_mk]
    rw [banachEquivL2_apply_coe (k := k) (x := Submodule.Quotient.mk x)]
    rw [banachEquivL2_apply_coe (k := k + 2) (x := Submodule.Quotient.mk x)]
    simp [toL2Quotₗ_mk]
    simpa using (diagPowInvCLM_two_toL2 (k := k) (x := x)).symm
  have h_incl :
      incl =
        iso₁Linv.comp ((diagPowInvCLM 2).comp iso₀L) := by
    calc
      incl = iso₁Linv.comp (iso₁L.comp incl) := by
        ext y
        simp [iso₁Linv, iso₁L, ContinuousLinearMap.comp_apply]
      _ = iso₁Linv.comp ((diagPowInvCLM 2).comp iso₀L) := by
        simpa [ContinuousLinearMap.comp_assoc] using congrArg (fun T => iso₁Linv.comp T) h_conj
  have h_diag : IsNuclearMap (diagPowInvCLM 2) :=
    isNuclearMap_diagPowInvCLM (s := 2) (by norm_num)
  have h_diag_pre : IsNuclearMap ((diagPowInvCLM 2).comp iso₀L) :=
    IsNuclearMap.comp_right (T := diagPowInvCLM 2) h_diag iso₀L
  have h_all :
      IsNuclearMap (iso₁Linv.comp ((diagPowInvCLM 2).comp iso₀L)) :=
    IsNuclearMap.comp_left (T := (diagPowInvCLM 2).comp iso₀L) h_diag_pre iso₁Linv
  simpa [incl, ← h_incl] using h_all

/-! ### The promised `NuclearSpaceStd` instance -/

noncomputable instance : NuclearSpaceStd RapidDecaySeq := by
  refine ⟨?_⟩
  refine ⟨(fun k : ℕ => seminorm k), ?_, withSeminorms, ?_⟩
  · exact seminorm_mono
  · intro k
    refine ⟨k + 2, Nat.lt_add_of_pos_right (n := k) (k := 2) (h := by decide), ?_⟩
    simpa using (isNuclearMap_inclCLM_succ_succ (k := k))

end RapidDecaySeq

end
end OSforGFF
