/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/

import Mathlib.Analysis.Distribution.SchwartzSpace.Basic
import Mathlib.Analysis.LocallyConvex.WithSeminorms

import OSforGFF.Basic
import OSforGFF.Spacetime.Defs
import OSforGFF.NuclearSpace.Defs
import OSforGFF.NuclearSpace.Std
import OSforGFF.NuclearSpace.Transport

/-!
# Schwartz seminorm sequence and (remaining) nuclearity gap

Mathlib equips the Schwartz space `𝓢(E, F)` with a locally convex topology generated by the
countable family of seminorms `SchwartzMap.seminorm 𝕜 k n`, bundled as
`schwartzSeminormFamily 𝕜 E F : (ℕ × ℕ) → Seminorm 𝕜 𝓢(E, F)`.

Our `NuclearSpaceStd` class (used by the Minlos/GFF pipeline) expects a **monotone** family
`p : ℕ → Seminorm ℝ E`. In this file we build such a family canonically for
`TestFunction = 𝓢(SpaceTime, ℝ)` by taking finite sups along the diagonal:

`p n = sup_{(k,m) ≤ (n,n)} schwartzSeminormFamily (k,m)`.

We prove:
- `Monotone schwartzSeminormSeq`;
- `WithSeminorms schwartzSeminormSeq`, i.e. it generates the existing Schwartz topology.

The **only** remaining (deep) ingredient needed to derive `NuclearSpaceStd TestFunction` is the
nuclearity of the local Banach inclusions for this specific seminorm sequence. We isolate this as
`SchwartzNuclearInclusion`.

In this repository, the spacetime Hermite development discharges this hypothesis: see
`OSforGFF.NuclearSpace.PhysHermiteSpaceTimeSchwartzNuclearInclusion` for a canonical instance.
-/

open scoped BigOperators

namespace OSforGFF

noncomputable section

open TopologicalSpace

/-! ## Generic Schwartz seminorm sequence on `𝓢(E, ℝ)` -/

namespace SchwartzSeq

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The underlying Schwartz seminorm family on `𝓢(E, ℝ)`, indexed by `ℕ × ℕ`. -/
abbrev schwartzSeminormFamily (E : Type*) [NormedAddCommGroup E] [NormedSpace ℝ E] :
    (ℕ × ℕ) → Seminorm ℝ (SchwartzMap E ℝ) :=
  _root_.schwartzSeminormFamily ℝ E ℝ

/-- A monotone `ℕ`-indexed seminorm family generating the Schwartz topology on `𝓢(E, ℝ)`, obtained by
taking finite sups over `Finset.Iic (n,n)`. -/
noncomputable def schwartzSeminormSeq (E : Type*) [NormedAddCommGroup E] [NormedSpace ℝ E] (n : ℕ) :
    Seminorm ℝ (SchwartzMap E ℝ) :=
  (Finset.Iic (n, n)).sup (schwartzSeminormFamily (E := E))

theorem schwartzSeminormSeq_mono : Monotone (schwartzSeminormSeq (E := E)) := by
  intro a b hab
  have hsubset : Finset.Iic (a, a) ⊆ Finset.Iic (b, b) := by
    intro x hx
    have hxle : x ≤ (a, a) := Finset.mem_Iic.mp hx
    have hab' : (a, a) ≤ (b, b) := Prod.mk_le_mk.2 ⟨hab, hab⟩
    exact Finset.mem_Iic.mpr (le_trans hxle hab')
  exact Finset.sup_mono hsubset

theorem schwartzSeminormSeq_withSeminorms : WithSeminorms (schwartzSeminormSeq (E := E)) := by
  -- Start from Mathlib's `WithSeminorms` for the `(ℕ × ℕ)`-indexed Schwartz family.
  let q : (ℕ × ℕ) → Seminorm ℝ (SchwartzMap E ℝ) := schwartzSeminormFamily (E := E)
  have hq : WithSeminorms q := by
    simpa [q, schwartzSeminormFamily] using
      (schwartz_withSeminorms (𝕜 := ℝ) (E := E) (F := ℝ))
  -- Replace `q` by its `Finset.Iic` partial sups. This does not change the topology.
  let q' : (ℕ × ℕ) → Seminorm ℝ (SchwartzMap E ℝ) := fun i => (Finset.Iic i).sup q
  have hq' : WithSeminorms q' := WithSeminorms.partial_sups (hp := hq)
  -- Restrict to the diagonal `n ↦ q' (n,n)`; this is cofinal, hence generates the same topology.
  let p : ℕ → Seminorm ℝ (SchwartzMap E ℝ) := fun n => q' (n, n)
  have hpq' : Seminorm.IsBounded q' p LinearMap.id := by
    intro n
    refine ⟨{(n, n)}, 1, ?_⟩
    simp [p, one_smul]
  have hq'p : Seminorm.IsBounded p q' LinearMap.id := by
    intro i
    refine ⟨{Nat.max i.1 i.2}, 1, ?_⟩
    have hle : q' i ≤ p (Nat.max i.1 i.2) := by
      have hi : i ≤ (Nat.max i.1 i.2, Nat.max i.1 i.2) :=
        Prod.mk_le_mk.2 ⟨le_max_left _ _, le_max_right _ _⟩
      have hsubset : Finset.Iic i ⊆ Finset.Iic (Nat.max i.1 i.2, Nat.max i.1 i.2) := by
        intro x hx
        exact Finset.mem_Iic.mpr (le_trans (Finset.mem_Iic.mp hx) hi)
      simpa [q', p] using (Finset.sup_mono hsubset)
    simpa [Seminorm.comp_apply, p, one_smul] using hle
  simpa [schwartzSeminormSeq, p, q'] using
    (WithSeminorms.congr (p := q') (q := p) (hp := hq') (hpq := hpq') (hqp := hq'p)
      : WithSeminorms p)

end SchwartzSeq

/-! ## A canonical monotone `ℕ`-family generating the Schwartz topology -/

/-- The underlying Schwartz seminorm family on `TestFunction`, indexed by `ℕ × ℕ`. -/
abbrev schwartzSeminormFamily_TestFunction : (ℕ × ℕ) → Seminorm ℝ TestFunction :=
  SchwartzSeq.schwartzSeminormFamily (E := SpaceTime)

/-- A monotone `ℕ`-indexed seminorm family generating the Schwartz topology, obtained by taking
finite sups over `Finset.Iic (n,n)`. -/
noncomputable def schwartzSeminormSeq (n : ℕ) : Seminorm ℝ TestFunction :=
  SchwartzSeq.schwartzSeminormSeq (E := SpaceTime) n

theorem schwartzSeminormSeq_mono : Monotone schwartzSeminormSeq := by
  simpa [schwartzSeminormSeq] using (SchwartzSeq.schwartzSeminormSeq_mono (E := SpaceTime))

theorem schwartzSeminormSeq_withSeminorms : WithSeminorms schwartzSeminormSeq := by
  simpa [schwartzSeminormSeq] using
    (SchwartzSeq.schwartzSeminormSeq_withSeminorms (E := SpaceTime))

/-! ## The remaining nuclearity assumption, in canonical Schwartz terms -/

open OSforGFF

/-- The **remaining** (deep) nuclearity step for the Schwartz space: for the canonical seminorm
sequence `schwartzSeminormSeq`, the local Banach inclusions are nuclear.

Assuming this, we get `NuclearSpaceStd TestFunction` without any `Classical.choose`
in the *choice of seminorm family* (only in the nuclearity proofs, if provided). -/
def SchwartzNuclearInclusion : Prop :=
  ∀ n : ℕ, ∃ m : ℕ, ∃ hnm : n < m,
    IsNuclearMap
      (BanachOfSeminorm.inclCLM (E := TestFunction)
        (p := schwartzSeminormSeq m)
        (q := schwartzSeminormSeq n)
        (by
          have hm := schwartzSeminormSeq_mono (a := n) (b := m) (Nat.le_of_lt hnm)
          exact hm))

/-- If `schwartzSeminormSeq` is equivalent (via `Seminorm.IsBounded … LinearMap.id`) to some other
monotone seminorm sequence with nuclear local inclusions, then the canonical
`SchwartzNuclearInclusion` hypothesis holds. -/
theorem schwartzNuclearInclusion_of_equivFamily
    {q : ℕ → Seminorm ℝ TestFunction} (hqmono : Monotone q)
    (hb_q_le_sch : Seminorm.IsBounded schwartzSeminormSeq q (LinearMap.id : TestFunction →ₗ[ℝ] TestFunction))
    (hb_sch_le_q : Seminorm.IsBounded q schwartzSeminormSeq (LinearMap.id : TestFunction →ₗ[ℝ] TestFunction))
    (hqNuclear : ∀ n : ℕ, ∃ m : ℕ, ∃ hnm : n < m,
      IsNuclearMap
        (BanachOfSeminorm.inclCLM (E := TestFunction) (p := q m) (q := q n)
          (hqmono (Nat.le_of_lt hnm)))) :
    SchwartzNuclearInclusion := by
  intro n
  rcases
      (NuclearSpaceStd.isNuclear_inclCLM_of_isBounded (E := TestFunction)
        (p := schwartzSeminormSeq) (q := q)
        schwartzSeminormSeq_mono hqmono hb_q_le_sch hb_sch_le_q hqNuclear n)
    with ⟨m, hnm, hNuc⟩
  refine ⟨m, hnm, ?_⟩
  simpa using hNuc

/-- A more canonical variant: if `q` is a monotone seminorm sequence that generates the Schwartz
topology (`WithSeminorms q`) and has nuclear local inclusions, then the canonical
`SchwartzNuclearInclusion` holds. -/
theorem schwartzNuclearInclusion_of_withSeminorms
    {q : ℕ → Seminorm ℝ TestFunction} (hqmono : Monotone q) (hq : WithSeminorms q)
    (hqNuclear : ∀ n : ℕ, ∃ m : ℕ, ∃ hnm : n < m,
      IsNuclearMap
        (BanachOfSeminorm.inclCLM (E := TestFunction) (p := q m) (q := q n)
          (hqmono (Nat.le_of_lt hnm)))) :
    SchwartzNuclearInclusion := by
  have hb_q_le_sch :
      Seminorm.IsBounded schwartzSeminormSeq q (LinearMap.id : TestFunction →ₗ[ℝ] TestFunction) :=
    WithSeminorms.isBounded_id (p := schwartzSeminormSeq) (q := q)
      schwartzSeminormSeq_withSeminorms hq
  have hb_sch_le_q :
      Seminorm.IsBounded q schwartzSeminormSeq (LinearMap.id : TestFunction →ₗ[ℝ] TestFunction) :=
    WithSeminorms.isBounded_id (p := q) (q := schwartzSeminormSeq)
      hq schwartzSeminormSeq_withSeminorms
  exact schwartzNuclearInclusion_of_equivFamily (q := q) hqmono hb_q_le_sch hb_sch_le_q hqNuclear

/-- If the canonical Schwartz nuclear-inclusion hypothesis holds, then `TestFunction` is a
`NuclearSpaceStd` in the sense used by the Minlos/GFF pipeline. -/
theorem nuclearSpaceStd_TestFunction_of_schwartzNuclearInclusion
    (hSch : SchwartzNuclearInclusion) : NuclearSpaceStd TestFunction := by
  refine ⟨?_⟩
  refine ⟨schwartzSeminormSeq, schwartzSeminormSeq_mono, schwartzSeminormSeq_withSeminorms, ?_⟩
  intro n
  rcases hSch n with ⟨m, hnm, hNuc⟩
  refine ⟨m, hnm, ?_⟩
  simpa using hNuc

end
end OSforGFF
